version: '3'

services:
  analyzer:
    build: './dineOutAnalyzer'
    ports:
      - "127.0.0.1:3000:3000"
  api:
    build: './dineOutApi'
    ports:
      - "127.0.0.1:5000:5000"
  recommender:
    build: './dineOutRecommender'
    ports:
      - "127.0.0.1:8000:8000"
  ui:
    build: './dineOutUI'
    ports:
      - "127.0.0.1:8080:8080"

